#!/usr/bin/env python3
"""Regenerate lib/pdf/font.ts — the font embedded in exported PDFs.

jsPDF's built-in fonts use WinAnsi encoding, which has no peso sign (U+20B1), so
every amount in the report would print as a missing glyph. This subsets DejaVu
Sans (regular + bold) down to the characters the report can actually contain and
emits them as base64 for jsPDF's virtual file system.

Requires fonttools and the DejaVu fonts:

    pip install fonttools
    apt-get install fonts-dejavu-core

    python3 scripts/build-pdf-font.py
"""

import base64
import os
import sys

from fontTools.subset import main as subset_main

FONT_DIR = "/usr/share/fonts/truetype/dejavu"
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "lib", "pdf", "font.ts")

# ASCII, Latin-1 Supplement and Latin Extended-A cover expense names such as
# "Piña" or "Café". The rest are the typographic marks and the peso sign.
CODEPOINTS = (
    list(range(0x20, 0x7F))
    + list(range(0xA0, 0x180))
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x20B1, 0x00B7]
)

STYLES = (("regular", "DejaVuSans.ttf"), ("bold", "DejaVuSans-Bold.ttf"))

HEADER = '''/**
 * Embedded font for PDF export.
 *
 * jsPDF's built-in fonts use WinAnsi encoding, which has no peso sign (U+20B1) —
 * amounts would render as missing glyphs. These are DejaVu Sans subsets covering
 * ASCII, Latin-1, Latin Extended-A and the typographic marks the report uses, so
 * the peso sign and names like "Pi\\u00f1a" print correctly.
 *
 * Generated by scripts/build-pdf-font.py — do not edit by hand.
 */

export const PDF_FONT_NAME = "DejaVuSans";

'''


def main() -> int:
    unicodes = ",".join(f"U+{code:04X}" for code in CODEPOINTS)
    encoded = {}

    for style, filename in STYLES:
        source = os.path.join(FONT_DIR, filename)
        if not os.path.exists(source):
            print(f"missing font: {source}", file=sys.stderr)
            return 1

        destination = f"/tmp/expense-tracker-{style}.ttf"
        subset_main([
            source,
            f"--unicodes={unicodes}",
            f"--output-file={destination}",
            # Keep the name table: jsPDF's TTF parser reads it, and stripping
            # it makes the font unusable even though it still validates.
            "--layout-features=",
            "--no-hinting",
            "--drop-tables+=GSUB,GPOS,GDEF,DSIG",
        ])

        with open(destination, "rb") as handle:
            data = handle.read()

        encoded[style] = base64.b64encode(data).decode("ascii")
        print(f"{style}: {len(data)} bytes")

    with open(OUTPUT, "w") as handle:
        handle.write(HEADER)
        handle.write(f'export const PDF_FONT_REGULAR_BASE64 =\n  "{encoded["regular"]}";\n\n')
        handle.write(f'export const PDF_FONT_BOLD_BASE64 =\n  "{encoded["bold"]}";\n')

    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
